### ISSUE TITLE
got an error when I input "make"

### ISSUE THREAD

**Issue by stbt121** [frank-y-liu/SPRNT#2]
Hello,
I am trying to build sprint and follow all of the steps based on the webpage. Commends that were used are:    ./configure, make dep and then I entered 'make' but I got an error said: 
make[1]: *** [sprnt] Error 1
make[1]: Leaving directory `/home/stabatabaeisadeghi/SPRNT/spt'
make: *** [all] Error 2

Here are the other errors: 
cc -O3 -fexceptions -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -m64 -fPIC -DNPARTITION -c -I../../AMD/Include -I../../AMD/Source -I../../COLAMD/Include -I/Lib -I../../CCOLAMD/Include -I../../CAMD/Include -I../Include -I../../UFconfig ../Core/cholmod_error.c

523c1523
< Total time:  0.00 seconds (CPU time),  0.01 seconds (wallclock time)
---
> Total time:  0.00 seconds (CPU time),  0.00 seconds (wallclock time)
make[3]: [run] Error 1 (ignored)
make[3]: Leaving directory `/home/stabatabaeisadeghi/SPRNT/ThirdParty/UF/SuiteSparse/UMFPACK/Demo'
cat Doc/License
UMFPACK Version 5.0, Copyright 1995-2006 by Timothy A. Davis.
All Rights Reserved.
UMFPACK is available under alternate licenses, contact T. Davis for details.

**Comment by frank-y-liu** [comment]
Fixed.

**Comment by stbt121** [comment]
Dear Dr. Liu,

I tried it again and I got the same error. Here are the errors:

sahar@sahar-VirtualBox:~/Desktop/SPRNT-master$ make
fatal: Not a git repository (or any of the parent directories): .git
cd /home/sahar/Desktop/SPRNT-master/src; make
make[1]: Entering directory '/home/sahar/Desktop/SPRNT-master/src'
fatal: Not a git repository (or any of the parent directories): .git
make[1]: 'libsprnt.a' is up to date.
make[1]: Leaving directory '/home/sahar/Desktop/SPRNT-master/src'
cd /home/sahar/Desktop/SPRNT-master/spt; make
make[1]: Entering directory '/home/sahar/Desktop/SPRNT-master/spt'
fatal: Not a git repository (or any of the parent directories): .git
g++ sim_parse.o run_spt.o new_parser.o  -o sprnt -O3
-L/home/sahar/Desktop/SPRNT-master/src -lsprnt
-L/home/sahar/Desktop/SPRNT-master/ThirdParty/CMLIB -ldbsplin -lblas
-lgfortran -m64 -lm -ldl
/home/sahar/Desktop/SPRNT-master/src/libsprnt.a(dspline.o): In function
`DSpline::Construct(double*, double*)':
dspline.C:(.text+0x23a): undefined reference to `dbknot_'
dspline.C:(.text+0x295): undefined reference to `dbintk_'
/home/sahar/Desktop/SPRNT-master/src/libsprnt.a(dspline.o): In function
`DSpline::EvalFun(double)':
dspline.C:(.text+0x356): undefined reference to `dbvalu_'
/home/sahar/Desktop/SPRNT-master/src/libsprnt.a(dspline.o): In function
`DSpline::EvalDer(double)':
dspline.C:(.text+0x426): undefined reference to `dbvalu_'
/home/sahar/Desktop/SPRNT-master/src/libsprnt.a(dspline.o): In function
`DSpline::EvalFunAndDer(double, double&, double&)':
dspline.C:(.text+0x51e): undefined reference to `dbvalu_'
dspline.C:(.text+0x57e): undefined reference to `dbvalu_'
collect2: error: ld returned 1 exit status
Makefile:45: recipe for target 'sprnt' failed
make[1]: *** [sprnt] Error 1
make[1]: Leaving directory '/home/sahar/Desktop/SPRNT-master/spt'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stbt121** [comment]
Tried again and it works. Thanks
